apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: hello-world-staging

resources:
- ../../apps/hello-world

patchesStrategicMerge:
- replica-patch.yaml

commonLabels:
  environment: staging
