apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: landing-page
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/nanolon/gitops.git
    targetRevision: feature/landing-page
    path: apps/landing-page
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - ApplyOutOfSyncOnly=true
  revisionHistoryLimit: 10
