apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- configmap.yaml
- deployment.yaml
- service.yaml
- ingress.yaml

commonLabels:
  app.kubernetes.io/name: landing-page
  app.kubernetes.io/version: "1.0"
  branch: feature-landing-page

namespace: default
